apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-go.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hello-go.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-go.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-go.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}