apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/deployment.yaml
namespace: prod
namePrefix: prod-
patchesStrategicMerge:
- env_patch.yaml
- memorylimit_patch.yaml
commonLabels:
  env: prod