apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app
spec:
  template:
    spec:
      containers:
        - name: go-demo-app
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 20Mi